#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {

    if [ "$per" -gt "90" ]; then
        icon=""
    elif [ "$per" -gt "80" ]; then
        icon=""
    elif [ "$per" -gt "70" ]; then
        icon=""
    elif [ "$per" -gt "60" ]; then
        icon=""
    elif [ "$per" -gt "50" ]; then
        icon=""
    elif [ "$per" -gt "40" ]; then
        icon=""
    elif [ "$per" -gt "30" ]; then
        icon=""
    elif [ "$per" -gt "20" ]; then
        icon=""
    elif [ "$per" -gt "10" ]; then
        icon=""
    elif [ "$per" -gt "0" ]; then
        icon=""
    else
        icon=""
    fi

    if [ $(cat "$bat/status") = Charging ]; then
        icon="${icon}"
    fi
    echo $icon
}

percent() {
    echo $per
}

time_left=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep time)

time_left() {
    echo $time_left
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "time" ] && time_left && exit
[ "$1" = "status" ] && echo $(cat "$bat/status") && exit
exit
