#!/bin/bash

get_status() {
    bluetoothctl show | grep PowerState | awk '{print $2}'
}

get_device() {
    if [ $(get_status) = on ]; then
        device=$(bluetoothctl devices Connected | awk '{$1=$2="";print substr($0,3)}')
        if [ "$device" = "" ]; then
            device="Not connected"
        fi
        icon=$(bluetoothctl info F4:4E:FD:00:08:67 | grep Icon | awk '{print $2}')
    fi
    echo $device
}

connect() {
    name="$@"
    uuid=$(bluetoothctl devices | grep "$name" | awk '{print $2}')
    bluetoothctl connect $uuid
}

toggle() {
    if [ $(get_status) = on ]; then
        bluetoothctl power off
    else
        bluetoothctl power on
    fi
}

available_devices() {
    if [ ! $(get_status) = "on" ]; then
        exit
    fi
    active=$(get_device)
    devices=$(bluetoothctl devices | awk '{$1=$2="";print substr($0,3)}' | head -n 10 | sed "s/${active}//" | grep -v '^[[:blank:]]*$')
    devices=$(sed 's/.*/"&"/' <<<"$devices" | tr '\n' ',')
    devices="[${devices%,}]"
    echo $devices
}

[ "$1" = "status" ] && get_status && exit
[ "$1" = "get-device" ] && get_device && exit
[ "$1" = "devices" ] && available_devices && exit
[ "$1" = "connect" ] && connect "${@:2}" && exit
[ "$1" = "toggle" ] && toggle && exit
exit
