#!/bin/sh

volume() {
    volume=$(pamixer --get-volume)
    echo $volume
}

icon () {

    if [ "$(pamixer --get-mute)" = "true" ]; then
        echo "󰖁"
        exit
    fi
    volume=$(volume)

    if [ $volume -ge 80 ]; then
        icon="󰕾"
    elif [ $volume -ge 30 ]; then
        icon="󰖀"
    else
        icon="󰕿"
    fi

    if [ "$(bluetooth)" = "true" ]; then
        icon="󰥰$icon"
    fi
    echo $icon
}

bluetooth() {
    if [ ! "$(pamixer --get-default-sink | grep bluez)" = "" ]; then
        echo true
    else
        echo false
    fi
}

[[ "$1" = "icon" ]] && icon && exit
[[ "$1" = "volume" ]] && volume && exit
[[ "$1" = "bluetooth-status" ]] && bluetooth && exit
exit
