-- Call all config files
require("plugins.config.lsp")
require("plugins.config.lspsaga")
require("plugins.config.null-ls")
require("plugins.config.cmp-nvim")
require("plugins.config.lualine")
require("plugins.config.telescope")
require("plugins.config.treesitter")
require("plugins.config.autopairs")
require("plugins.config.bufferline")
require("plugins.config.nvim-tree")
require("plugins.config.toggleterm")
require("plugins.config.comment")
require("plugins.config.dap-nvim")
require("plugins.config.noice-nvim")
