[alias] # command aliases
b = "build"
br = "build --release"
t = "test -- --nocapture"
tw = "test --workspace -- --nocapture"
r = "run"
rr = "run --release"

[build]
incremental = true

[term]
color = "always"
