[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 11.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Book"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Book"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Book"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Book"

[scrolling]
history = 50000

[window]
opacity = 0.8
